clean:
	rm -f infile.ssposcar
	rm -f infile.forceconstant
	rm -f infile.forces
	rm -f infile.meta
	rm -f infile.positions
	rm -f infile.stat
	rm -f outfile.*
	rm -rf samples
	rm -rf stride_*
	rm -f plot_dos_convergence.py
	rm -f plot_DOS_convergence.pdf
