clean:
	rm -f extract_force*.log
	rm -f outfile.*
	rm -f infile.forces
	rm -f infile.meta
	rm -f infile.positions
	rm -f infile.stat
	rm -rf samples
	rm -rf rc_polar_*
	rm -f infile.forceconstant
	rm -f original.forceconstant
